// src/AngularJS/myApp0/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'myApp0';
}

<!--
 * @Author: QuestionMark001
 * @Date: 2023-06-22 19:14:52
 * @LastEditors: QuestionMark001
 * @LastEditTime: 2023-06-22 23:26:40
 * @FilePath: /LocalProjects/WebEx/src/AngularJS/myApp0/src/app/app.component.html
 * @Description: myApp0 - Hello Component
 * 
 * Copyright (c) 2023 by QuestionMark001, All Rights Reserved. 
-->

<style>
    h1 {
        font-family: Roboto, Helvetica Neue Light, Helvetica Neue, Helvetica, Arial, Lucida Grande, sans-serif;
    }
</style>

<!-- Hello World! -->
<div>
    <h1>Hello World!</h1>
</div>

// src/Vue.js/12-hello-dog-2/src/App.vue
<!--
 * @Author: QuestionMark001
 * @Date: 2023-04-27 14:43:18
 * @LastEditors: QuestionMark001
 * @LastEditTime: 2023-05-04 15:30:58
 * @FilePath: /LocalProjects/WebEx/src/Vue.js/12-hello-dog-2/src/App.vue
 * @Description: 12-hello-dog-2 App.vue
 * 
 * Copyright (c) 2023 by QuestionMark001, All Rights Reserved. 
-->
<template>
    <div>
        <DogCom2></DogCom2>
        <DogCom2></DogCom2>
        <DogCom2></DogCom2>
        <DogCom2></DogCom2>
        <DogCom2></DogCom2>
    </div>
</template>

<script>
import DogCom2 from './components/dogCom2.vue'

export default {
    components: {
        DogCom2
    }
}
</script>

<style scoped></style>
