// src/Vue_3.x/vue-search/src/App.vue
<!--
 * @Author: QuestionMark001
 * @Date: 2023-05-18 15:19:42
 * @LastEditors: QuestionMark001
 * @LastEditTime: 2023-05-18 16:24:28
 * @FilePath: /LocalProjects/WebEx/src/Vue_3.x/vue-search/src/App.vue
 * @Description: Vue Search Vue App
 * 
 * Copyright (c) 2023 by QuestionMark001, All Rights Reserved. 
-->

<script setup>
import Search from './components/Search.vue';
</script>

<template>
<Search></Search>
</template>

<style scoped></style>

// src/AngularJS/myApp0/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'myApp0';
}

<!--
 * @Author: QuestionMark001
 * @Date: 2023-06-22 19:14:52
 * @LastEditors: QuestionMark001
 * @LastEditTime: 2023-06-22 23:26:40
 * @FilePath: /LocalProjects/WebEx/src/AngularJS/myApp0/src/app/app.component.html
 * @Description: myApp0 - Hello Component
 * 
 * Copyright (c) 2023 by QuestionMark001, All Rights Reserved. 
-->

<style>
    h1 {
        font-family: Roboto, Helvetica Neue Light, Helvetica Neue, Helvetica, Arial, Lucida Grande, sans-serif;
    }
</style>

<!-- Hello World! -->
<div>
    <h1>Hello World!</h1>
</div>
