// src/Vant UI/01_Button/src/App.vue
<!--
 * @Author: QuestionMark001
 * @Date: 2023-04-29 15:09:52
 * @LastEditors: QuestionMark001
 * @LastEditTime: 2023-04-29 16:38:13
 * @FilePath: /LocalProjects/WebEx/src/Vant UI/01_Button/src/App.vue
 * @Description: 01_Button App.vue
 * 
 * Copyright (c) 2023 by QuestionMark001, All Rights Reserved. 
-->
<script setup>
import Button from './components/Button.vue'
</script>

<template>
    <div id="div_btn">
        <Button />
    </div>
</template>

// src/AngularJS/myApp0/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'myApp0';
}

<!--
 * @Author: QuestionMark001
 * @Date: 2023-06-22 19:14:52
 * @LastEditors: QuestionMark001
 * @LastEditTime: 2023-06-22 23:26:40
 * @FilePath: /LocalProjects/WebEx/src/AngularJS/myApp0/src/app/app.component.html
 * @Description: myApp0 - Hello Component
 * 
 * Copyright (c) 2023 by QuestionMark001, All Rights Reserved. 
-->

<style>
    h1 {
        font-family: Roboto, Helvetica Neue Light, Helvetica Neue, Helvetica, Arial, Lucida Grande, sans-serif;
    }
</style>

<!-- Hello World! -->
<div>
    <h1>Hello World!</h1>
</div>
